### ISSUE TITLE
Any chance with "No block bodies to write in this log period"?  (Fixed by restart)

### ISSUE THREAD

**Issue by egorFiNE** [ledgerwatch/erigon#6585]
Our BSC nodes went from having this every other day to going down every 30-60 minutes once we have upgraded erigon from 2.32 to 2.34 today.

Any chance for an update fixing this anytime soon? 

Update: thanks to suggestion by @mandrigin this is fixable by a restart, no need to unwind.

**Comment by mandrigin** [comment]
@revitteth I think its the same that we experienced.

@egorFiNE restart helps, right?

**Comment by egorFiNE** [comment]
@mandrigin conveniently I have got at least one failed BSC node, so trying now.

**Comment by egorFiNE** [comment]
@mandrigin indeed it is! A simple restart fixed this issue momentarily.

**Comment by nikolinsko** [comment]
maybe try to build based on this commit: https://github.com/ledgerwatch/erigon/commit/7bf937274095643941919736df612aaecc08de5a

my node has not had any issues over a week on that.

 Changed to v2.34 and had the issue within an hour, resetting to the commit seemed to fix the issue.

Just a guess ;)

i'm also running this script since a few weeks which should scan the last log line for 'No blocks' and restarts the client. ( There are definately better ways to do this, last time a touched perl was during uni, but seems to work fine)

```
#!/usr/bin/perl

open(my $fd, "<", "/var/log/supervisor/erigon.err.log") or die "Can't open log";
$at_end = 0;
$at_end_recurring = 0;

while(1) {
    if(eof $fd) {
        sleep 1;
        $fd->clearerr;
        if(at_end_recurring == 10){
          system('echo $(date -u) no new logs re-opening');
          open(my $fd, "<", "/var/log/supervisor/erigon.err.log") or die "Can't open log";
        }
        if($at_end == 0){
          system('echo $(date -u) on last log line');
          $at_end = 1;
        } 
        $at_end_recurring += 1;
        next;
    }
    my $line = <$fd>;
    chomp($line);
    $at_end_recurring = 0;
    if($at_end == 0){
      next;
    }
    if($line =~ /No block headers/) {
        system('echo $(date -u) erigon stuck - restarting');
        system("supervisorctl restart erigon");
        
    }
}
```

**Comment by mandrigin** [comment]
Yeah, that means it’s the same issue I am having every now and then. If I get it myself, I can try to investigate. Maybe if your node gets stuck, let it be there for 1-2 hours and then do SIGQUIT on it and paste the goroutines trace here.

https://stackoverflow.com/a/35290196

**Comment by egorFiNE** [comment]
@nikolinsko thank you! I will try to rebase on this commit the next time it fails

Somehow it is running for about 14 hours now with no failures.

**Comment by egorFiNE** [comment]
nvm, trying 2.35.0 now

**Comment by asa-prmxbt** [comment]
Having same on 2.35.0

**Comment by fenidik** [comment]
Having same on 2.35.0

**Comment by egorFiNE** [comment]
@fenidik can confirm.

**Comment by mandrigin** [comment]
logs could be useful here, with about an hour before it is stuck, and an hour after

**Comment by koraykoska** [comment]
Is there any workaround for this right now? This is really annoying

**Comment by egorFiNE** [comment]
@Aderks same here, I'm unable to launch polygon node on erigon, it stucks.

**Comment by egorFiNE** [comment]
Yesterday I had "no block bodies" fail 3 times within about 15 minutes on BSC. I have to give it up at that point.

**Comment by egorFiNE** [comment]
I'm having this issue every 30 minutes now.

**Comment by AdminAnticaptcha** [comment]
I think something is wrong with peer management, I've set a limit of 500 peers and at some point this limit is fully used and probably consists only of unsynced or fake peers.

**Comment by Aderks** [comment]
Credit goes to a member of The Graph Discord, Adorid | SGTstake

Added this flag `--bodies.cache=21474836480` and I was able to get passed Stage 5 and things are looking healthy. See if it helps...

**Comment by AdminAnticaptcha** [comment]
@egorFiNE , did you try @nikolinsko's suggestion with that special commit ?

**Comment by egorFiNE** [comment]
@AdminAnticaptcha nope, I have seen 2.35 released and assumed that all urgent pending issues were fixed in it, so did not try to roll back.

**Comment by fenidik** [comment]
> 



> Added this flag `--bodies.cache=21474836480` and I was able to get passed Stage 5 and things are looking healthy. See if it helps...

It helped me at least bypass 5/16 Bodies. Thanks

**Comment by AlexeyAkhunov** [comment]
Please try using `v2.35.2` it has specific fix for that

**Comment by koraykoska** [comment]
And bodies.cache will not be necessary with the new version?

**Comment by koraykoska** [comment]
@AlexeyAkhunov I just checked. And in fact it does not only still not work, but also breaks the fix with bodies.cache. So now it's not possible at all to get past this issue.

**Comment by AlexeyAkhunov** [comment]
@koraykoska Would you be able to show full log since restart please?

**Comment by egorFiNE** [comment]
@AlexeyAkhunov I'm trying to reproduce now with 2.35.2. Although my node on 2.35.1 had no glitches for 12h+ at this time, so I'm not sure if I could reproduce. I will post logs once and if it happens.

**Comment by egorFiNE** [comment]
Still no glitches.

**Comment by AdminAnticaptcha** [comment]
2.36.0 didn't help, same stalling:
`INFO[01-21|03:48:30.211] [7/16 Execution] Blocks execution        from=24966757 to=24966786
INFO[01-21|03:48:31.650] [7/16 Execution] Completed on            block=24966786
INFO[01-21|03:48:31.650] [8/16 HashState] Promoting plain state   from=24966757 to=24966786
INFO[01-21|03:48:31.650] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=true csbucket=AccountChangeSet
INFO[01-21|03:48:31.696] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=false csbucket=AccountChangeSet
INFO[01-21|03:48:31.822] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=false csbucket=StorageChangeSet
INFO[01-21|03:48:32.267] [9/16 IntermediateHashes] Generating intermediate hashes from=24966757 to=24966786
INFO[01-21|03:48:33.648] [10/16 CallTraces] Pruned call trace intermediate table from=24876757 to=24876785
INFO[01-21|03:48:35.296] Commit cycle                             in=521.667692ms
INFO[01-21|03:48:35.296] Timings (slower than 50ms)               Headers=7m13.132s Bodies=4.814s Execution=1.438s HashState=617ms IntermediateHashes=1.371s CallTraces=276ms AccountHistoryIndex=136ms StorageHistoryIndex=375ms LogIndex=213ms TxLookup=132ms
INFO[01-21|03:48:35.296] Tables                                   PlainState=202.9GB AccountChangeSet=1.3GB StorageChangeSet=2.7GB BlockTransaction=2.9GB TransactionLog=6.1GB FreeList=1.8GB ReclaimableSpace=1.8TB
INFO[01-21|03:48:35.296] RPC Daemon notified of new headers       from=24966757 to=24966786 hash=0x592c5b2ceaf6f772d6592978945e0d1fc3f3e91b7ecf7b65a2ce1ee77c974fa3 header sending=28.973µs log sending=310ns
INFO[01-21|03:48:36.318] [2/16 Headers] Waiting for headers...    from=24966786
INFO[01-21|03:48:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:49:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:49:20.871] [txpool] stat                            block=24966786 pending=5320 baseFee=0 queued=3231 alloc=4.0GB sys=6.2GB
INFO[01-21|03:49:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:49:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:50:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:50:16.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=15 respMin=24966786 respMax=24966786 dups=15
INFO[01-21|03:50:19.722] [p2p] GoodPeers                          eth66=492 eth67=48
INFO[01-21|03:50:20.871] [txpool] stat                            block=24966786 pending=5840 baseFee=0 queued=3567 alloc=4.9GB sys=6.2GB
INFO[01-21|03:50:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:50:36.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=24966786 skelMax=25261698 resp=12 respMin=24966786 respMax=24966786 dups=12
INFO[01-21|03:50:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:50:56.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=17 respMin=24966786 respMax=24966786 dups=17
INFO[01-21|03:51:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:51:16.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24966786 dups=14
INFO[01-21|03:51:20.872] [txpool] stat                            block=24966786 pending=6340 baseFee=0 queued=3760 alloc=3.1GB sys=6.2GB
INFO[01-21|03:51:36.319] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:51:36.319] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=24966786 skelMax=25261698 resp=11 respMin=24966786 respMax=24966786 dups=11
INFO[01-21|03:51:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:51:56.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=17 respMin=24966786 respMax=24966786 dups=17
INFO[01-21|03:52:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:52:16.318] Req/resp stats                           req=5 reqMin=24966869 reqMax=24967061 skel=13 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24967062 dups=13
INFO[01-21|03:52:19.722] [p2p] GoodPeers                          eth66=492 eth67=49
INFO[01-21|03:52:20.871] [txpool] stat                            block=24966786 pending=6823 baseFee=0 queued=4060 alloc=3.9GB sys=6.2GB
INFO[01-21|03:52:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:52:36.318] Req/resp stats                           req=8 reqMin=24966869 reqMax=24967071 skel=15 skelMin=24966786 skelMax=25261698 resp=15 respMin=24966786 respMax=24967072 dups=14
INFO[01-21|03:52:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:52:56.318] Req/resp stats                           req=5 reqMin=24966869 reqMax=24967071 skel=13 skelMin=24966786 skelMax=25261698 resp=13 respMin=24966786 respMax=24966786 dups=13
INFO[01-21|03:53:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:53:16.318] Req/resp stats                           req=2 reqMin=24966879 reqMax=24967071 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24966786 dups=14
INFO[01-21|03:53:20.869] [txpool] stat                            block=24966786 pending=7151 baseFee=0 queued=4253 alloc=2.9GB sys=6.2GB
INFO[01-21|03:53:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:53:36.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=24966786 skelMax=25261698 resp=13 respMin=24966786 respMax=24966786 dups=13
INFO[01-21|03:53:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
INFO[01-21|03:53:56.318] Req/resp stats                           req=4 reqMin=24966906 reqMax=24967098 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24967099 dups=13`

**Comment by AlexeyAkhunov** [comment]
> 2.36.0 didn't help, same stalling:
> 
> ```
> INFO[01-21|03:48:31.650] [7/16 Execution] Completed on            block=24966786
> INFO[01-21|03:48:31.650] [8/16 HashState] Promoting plain state   from=24966757 to=24966786
> INFO[01-21|03:48:31.650] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=true csbucket=AccountChangeSet
> INFO[01-21|03:48:31.696] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=false csbucket=AccountChangeSet
> INFO[01-21|03:48:31.822] [8/16 HashState] Incremental promotion   from=24966757 to=24966786 codes=false csbucket=StorageChangeSet
> INFO[01-21|03:48:32.267] [9/16 IntermediateHashes] Generating intermediate hashes from=24966757 to=24966786
> INFO[01-21|03:48:33.648] [10/16 CallTraces] Pruned call trace intermediate table from=24876757 to=24876785
> INFO[01-21|03:48:35.296] Commit cycle                             in=521.667692ms
> INFO[01-21|03:48:35.296] Timings (slower than 50ms)               Headers=7m13.132s Bodies=4.814s Execution=1.438s HashState=617ms IntermediateHashes=1.371s CallTraces=276ms AccountHistoryIndex=136ms StorageHistoryIndex=375ms LogIndex=213ms TxLookup=132ms
> INFO[01-21|03:48:35.296] Tables                                   PlainState=202.9GB AccountChangeSet=1.3GB StorageChangeSet=2.7GB BlockTransaction=2.9GB TransactionLog=6.1GB FreeList=1.8GB ReclaimableSpace=1.8TB
> INFO[01-21|03:48:35.296] RPC Daemon notified of new headers       from=24966757 to=24966786 hash=0x592c5b2ceaf6f772d6592978945e0d1fc3f3e91b7ecf7b65a2ce1ee77c974fa3 header sending=28.973µs log sending=310ns
> INFO[01-21|03:48:36.318] [2/16 Headers] Waiting for headers...    from=24966786
> INFO[01-21|03:48:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:49:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:49:20.871] [txpool] stat                            block=24966786 pending=5320 baseFee=0 queued=3231 alloc=4.0GB sys=6.2GB
> INFO[01-21|03:49:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:49:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:50:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:50:16.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=15 respMin=24966786 respMax=24966786 dups=15
> INFO[01-21|03:50:19.722] [p2p] GoodPeers                          eth66=492 eth67=48
> INFO[01-21|03:50:20.871] [txpool] stat                            block=24966786 pending=5840 baseFee=0 queued=3567 alloc=4.9GB sys=6.2GB
> INFO[01-21|03:50:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:50:36.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=24966786 skelMax=25261698 resp=12 respMin=24966786 respMax=24966786 dups=12
> INFO[01-21|03:50:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:50:56.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=17 respMin=24966786 respMax=24966786 dups=17
> INFO[01-21|03:51:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:51:16.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24966786 dups=14
> INFO[01-21|03:51:20.872] [txpool] stat                            block=24966786 pending=6340 baseFee=0 queued=3760 alloc=3.1GB sys=6.2GB
> INFO[01-21|03:51:36.319] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:51:36.319] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=15 skelMin=24966786 skelMax=25261698 resp=11 respMin=24966786 respMax=24966786 dups=11
> INFO[01-21|03:51:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:51:56.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=24966786 skelMax=25261698 resp=17 respMin=24966786 respMax=24966786 dups=17
> INFO[01-21|03:52:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:52:16.318] Req/resp stats                           req=5 reqMin=24966869 reqMax=24967061 skel=13 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24967062 dups=13
> INFO[01-21|03:52:19.722] [p2p] GoodPeers                          eth66=492 eth67=49
> INFO[01-21|03:52:20.871] [txpool] stat                            block=24966786 pending=6823 baseFee=0 queued=4060 alloc=3.9GB sys=6.2GB
> INFO[01-21|03:52:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:52:36.318] Req/resp stats                           req=8 reqMin=24966869 reqMax=24967071 skel=15 skelMin=24966786 skelMax=25261698 resp=15 respMin=24966786 respMax=24967072 dups=14
> INFO[01-21|03:52:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:52:56.318] Req/resp stats                           req=5 reqMin=24966869 reqMax=24967071 skel=13 skelMin=24966786 skelMax=25261698 resp=13 respMin=24966786 respMax=24966786 dups=13
> INFO[01-21|03:53:16.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:53:16.318] Req/resp stats                           req=2 reqMin=24966879 reqMax=24967071 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24966786 dups=14
> INFO[01-21|03:53:20.869] [txpool] stat                            block=24966786 pending=7151 baseFee=0 queued=4253 alloc=2.9GB sys=6.2GB
> INFO[01-21|03:53:36.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:53:36.318] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=24966786 skelMax=25261698 resp=13 respMin=24966786 respMax=24966786 dups=13
> INFO[01-21|03:53:56.318] [2/16 Headers] No block headers to write in this log period block number=24966786
> INFO[01-21|03:53:56.318] Req/resp stats                           req=4 reqMin=24966906 reqMax=24967098 skel=14 skelMin=24966786 skelMax=25261698 resp=14 respMin=24966786 respMax=24967099 dups=13```
> ```

That's BSC, right? This is a different problem, will be looking to solve this later

**Comment by egorFiNE** [comment]
Still no glitches. :-\ 

I'm gonna try to get back that erigon node back into production. Maybe that's the volume of RPC requests that causes it.

**Comment by AlexeyAkhunov** [comment]
@AdminAnticaptcha I have prepared some improvements for BSC headers stuck issue, but need more testing: https://github.com/ledgerwatch/erigon/pull/6653

For me it did improve things a lot

**Comment by AdminAnticaptcha** [comment]
@AlexeyAkhunov I'm testing this commit now, will report later.

**Comment by AdminAnticaptcha** [comment]
@AlexeyAkhunov I noticed that things got somehow better, but not ideal. At first the blocks come normally one by one, then start to come in batches which delays the node sync. My script compares latest block number from bscscan against eth_blockNumber and restarts the node. After restart things go normally for some time and behavior repeats again.
Here's the log from start till kill: https://gist.github.com/AdminAnticaptcha/5d4bc6d51ff2e4247ab7787737cd1bfc

**Comment by AlexeyAkhunov** [comment]
@AdminAnticaptcha Thank you, I have merged it since it made improvements. Would you be able to try this one with more tweaks: https://github.com/ledgerwatch/erigon/pull/6662

Thanks a lot in advance!

**Comment by AdminAnticaptcha** [comment]
@AlexeyAkhunov I'm running it for 3 hours already with perfect sync! I'll update after 24h, thanks!

**Comment by egorFiNE** [comment]
My node had no glitches during this time but commited suicide instead. 

It started with `No block bodies to write in this log period` followed by snapshots build and then `fatal error: concurrent map iteration and map write` with a huge stack trace (attached) and then on restart `read_header:16413 no usable meta-pages, database is corrupted`.

Hardware is fine. No memory (or other) errors reported by kernel. SMART attributes and logs of the drive are clear. Filesystem is fine. Free space is plenty. No reserved blocks.

[erigon-suicide-log.txt](https://github.com/ledgerwatch/erigon/files/10478941/erigon-suicide-log.txt)

**Comment by egorFiNE** [comment]
@AlexeyAkhunov BTW I can give you the ssh root access to the node if you need it for debugging. Let me know if that would help and also let me know if I you need a bootstrapped working BSC there prior.

**Comment by AdminAnticaptcha** [comment]
@AlexeyAkhunov the node is working for more than 24h without interruption. Many thanks!

**Comment by nikolinsko** [comment]
@AdminAnticaptcha @egorFiNE could you provide an update? Thanks :)

**Comment by AdminAnticaptcha** [comment]
@nikolinsko Nothing changed since my last post, node is running very stable.

**Comment by Aderks** [comment]
Polygon Archival: Using `v2.36.1` & `2.37.0` we still have issues with the "No block bodies to write ..." problem (restart fixes it).

We're currently running `v2.36.0` with `--bodies.cache=21474836480` flag still in place and so far about ~2 days in with no issues regarding the "No block bodes to write ...". So not sure if something was changed after `v2.36.0` or we're just lucky using `v2.36.0`. Curious what others are still seeing.

**Comment by egorFiNE** [comment]
@AdminAnticaptcha we had to decommission BSC erigon node after it committed suicide. 

Mainnet Erigon node is rock stable.

**Comment by seonggwonyoon** [comment]
This is the problem I'm experiencing from v2.35.0 to v2.37.0.
I've tried increasing max.peer and bodies.cache, but it doesn't seem to solve anything.

My guess is that the number of peers decreases when block sync stops.

**Comment by koraykoska** [comment]
@AlexeyAkhunov Here you go:

```
[WARN] [02-02|09:25:58.031] no log dir set, console logging only
[INFO] [02-02|09:25:58.031] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
[INFO] [02-02|09:25:58.031] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
[WARN] [02-02|09:25:58.036] no log dir set, console logging only
[INFO] [02-02|09:25:58.036] Build info                               git_branch=stable git_tag=v2.37.0-dirty git_commit=12419c759162fdba03e645d0cb8d21e582e067a5
[INFO] [02-02|09:25:58.037] Starting Erigon on Bor Mainnet...
[INFO] [02-02|09:25:58.037] Maximum peer count                       ETH=400 total=400
[INFO] [02-02|09:25:58.038] starting HTTP APIs                       APIs=eth,net,web3,bor,trace,debug
[INFO] [02-02|09:25:58.038] torrent verbosity                        level=WRN
[INFO] [02-02|09:25:58.038] [torrent] Public IP                      ip=5.199.170.110
[INFO] [02-02|09:25:58.039] Set global gas cap                       cap=50000000
[INFO] [02-02|09:25:58.040] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=512mb upload.rate=4mb
[INFO] [02-02|09:25:58.041] Opening Database                         label=chaindata path=/home/erigon/.local/share/erigon/chaindata
[INFO] [02-02|09:25:58.048] Initialised chain configuration          config="{ChainID: 137, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: <nil>, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Engine: bor}" genesis=0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b
[INFO] [02-02|09:25:58.048] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false
[INFO] [02-02|09:26:03.102] Initialising Ethereum protocol           network=137
[INFO] [02-02|09:26:06.835] Starting private RPC server              on=127.0.0.1:9090
[INFO] [02-02|09:26:06.835] new subscription to logs established
[INFO] [02-02|09:26:06.835] rpc filters: subscribing to Erigon events
[INFO] [02-02|09:26:06.835] new subscription to newHeaders established
[INFO] [02-02|09:26:06.835] New txs subscriber joined
[INFO] [02-02|09:26:06.836] Reading JWT secret                       path=/home/erigon/.local/share/erigon/jwt.hex
[INFO] [02-02|09:26:06.836] HTTP endpoint opened for Engine API      url=0.0.0.0:8551 ws=true ws.compression=true
[INFO] [02-02|09:26:06.837] HTTP endpoint opened                     url=0.0.0.0:8546 ws=true ws.compression=true grpc=false
[INFO] [02-02|09:26:06.839] Started P2P networking                   version=66 self=enode://588a6807789aa8e72a80ba8fb0b3c2a7d2ff9477126f32d1fc57b3adc7731a307730d5a45e7aa11f5f74b9641cd87943f20d8ed3989ca979aa960a05ce6a4c94@5.199.170.110:30304 name=erigon/v2.37.0-stable-12419c75/linux-amd64/go1.19.5
[INFO] [02-02|09:26:06.846] [txpool] Started
[WARN] [02-02|09:26:06.850] [1/15 Snapshots] downloading missing snapshots
[INFO] [02-02|09:26:06.850] [1/15 Snapshots] Fetching torrent files metadata
[WARN] [02-02|09:26:06.855] [1/15 Snapshots] Some blocks are not in snapshots and not in db max_in_snapshots=28999999 min_in_db=37983400
[INFO] [02-02|09:26:06.855] [Snapshots] Blocks Stat                  blocks=29000k indices=29000k alloc=2.1GB sys=3.1GB
[INFO] [02-02|09:26:06.855] [2/15 Headers] Waiting for headers...    from=38669681
[INFO] [02-02|09:26:26.855] [2/15 Headers] Wrote block headers       number=38670449 blk/second=38.400 alloc=2.4GB sys=3.1GB
[INFO] [02-02|09:26:46.856] [2/15 Headers] Wrote block headers       number=38709809 blk/second=1968.000 alloc=3.6GB sys=3.9GB
[INFO] [02-02|09:27:06.837] [txpool] stat                            block=38669522 pending=98 baseFee=48 queued=5776 alloc=3.0GB sys=4.3GB
[INFO] [02-02|09:27:06.855] [2/15 Headers] Wrote block headers       number=38749169 blk/second=1968.000 alloc=3.0GB sys=4.3GB
[INFO] [02-02|09:27:26.856] [2/15 Headers] Wrote block headers       number=38750513 blk/second=67.200 alloc=3.3GB sys=4.3GB
[INFO] [02-02|09:27:46.056] [2/15 Headers] Processed                 highest inserted=38817655 age=2s
[INFO] [02-02|09:27:46.056] [2/15 Headers] DONE                      in=1m39.200795176s
[INFO] [02-02|09:27:57.570] [5/15 Bodies] Processing bodies...       from=38669681 to=38817655
[INFO] [02-02|09:28:03.102] [p2p] GoodPeers                          eth66=15
[INFO] [02-02|09:28:06.839] [txpool] stat                            block=38669522 pending=200 baseFee=97 queued=9917 alloc=2.4GB sys=5.0GB
[INFO] [02-02|09:28:17.570] [5/15 Bodies] Downloading block bodies   block_num=38669764 delivery/sec=18.3MB wasted/sec=0B remaining=147890 delivered=6862 cache=256.0MB alloc=3.4GB sys=5.2GB
[INFO] [02-02|09:28:37.577] [5/15 Bodies] Downloading block bodies   block_num=38669806 delivery/sec=11.7MB wasted/sec=0B remaining=147848 delivered=10983 cache=256.0MB alloc=2.6GB sys=5.8GB
[INFO] [02-02|09:28:57.588] [5/15 Bodies] Downloading block bodies   block_num=38672574 delivery/sec=70.6MB wasted/sec=0B remaining=145080 delivered=34956 cache=256.0MB alloc=4.7GB sys=6.0GB
[INFO] [02-02|09:29:06.835] [txpool] stat                            block=38669522 pending=281 baseFee=144 queued=13926 alloc=2.7GB sys=6.1GB
[INFO] [02-02|09:29:17.576] [5/15 Bodies] Downloading block bodies   block_num=38676555 delivery/sec=98.6MB wasted/sec=0B remaining=141099 delivered=69200 cache=256.0MB alloc=4.6GB sys=6.1GB
[INFO] [02-02|09:29:37.588] [5/15 Bodies] Downloading block bodies   block_num=38679012 delivery/sec=92.8MB wasted/sec=0B remaining=138642 delivered=101620 cache=256.0MB alloc=3.7GB sys=6.1GB
[INFO] [02-02|09:29:57.570] [5/15 Bodies] Downloading block bodies   block_num=38679755 delivery/sec=91.8MB wasted/sec=0B remaining=137899 delivered=136488 cache=256.0MB alloc=5.0GB sys=6.1GB
[INFO] [02-02|09:30:03.103] [p2p] GoodPeers                          eth66=27
[INFO] [02-02|09:30:06.847] [txpool] stat                            block=38669522 pending=349 baseFee=189 queued=16020 alloc=3.9GB sys=6.1GB
[INFO] [02-02|09:30:17.570] [5/15 Bodies] Downloading block bodies   block_num=38682535 delivery/sec=27.3MB wasted/sec=0B remaining=135119 delivered=146587 cache=256.0MB alloc=2.7GB sys=6.1GB
[INFO] [02-02|09:30:37.570] [5/15 Bodies] Downloading block bodies   block_num=38684837 delivery/sec=8.2MB wasted/sec=0B remaining=132817 delivered=149891 cache=256.0MB alloc=3.6GB sys=6.1GB
[INFO] [02-02|09:30:57.570] [5/15 Bodies] Downloading block bodies   block_num=38684856 delivery/sec=1.4MB wasted/sec=0B remaining=132798 delivered=150366 cache=256.0MB alloc=3.8GB sys=6.1GB
[INFO] [02-02|09:31:07.867] [txpool] stat                            block=38669522 pending=492 baseFee=235 queued=18681 alloc=3.9GB sys=6.1GB
[INFO] [02-02|09:31:17.571] [5/15 Bodies] Downloading block bodies   block_num=38684897 delivery/sec=112.1KB wasted/sec=0B remaining=132757 delivered=150387 cache=251.9MB alloc=3.9GB sys=6.1GB
[INFO] [02-02|09:31:37.571] [5/15 Bodies] Downloading block bodies   block_num=38685973 delivery/sec=20.5MB wasted/sec=0B remaining=131681 delivered=156652 cache=256.0MB alloc=3.5GB sys=6.1GB
[INFO] [02-02|09:31:57.570] [5/15 Bodies] Downloading block bodies   block_num=38685973 delivery/sec=4.9MB wasted/sec=0B remaining=131681 delivered=158226 cache=256.0MB alloc=4.0GB sys=6.1GB
[INFO] [02-02|09:32:03.102] [p2p] GoodPeers                          eth66=34
[INFO] [02-02|09:32:06.842] [txpool] stat                            block=38669522 pending=558 baseFee=284 queued=20624 alloc=4.4GB sys=6.1GB
[INFO] [02-02|09:32:17.576] [5/15 Bodies] Downloading block bodies   block_num=38689895 delivery/sec=13.4MB wasted/sec=0B remaining=127759 delivered=162895 cache=179.1MB alloc=2.8GB sys=6.1GB
[INFO] [02-02|09:32:37.570] [5/15 Bodies] Downloading block bodies   block_num=38689895 delivery/sec=2.3MB wasted/sec=0B remaining=127759 delivered=163686 cache=224.1MB alloc=3.1GB sys=6.1GB
[INFO] [02-02|09:32:57.570] [5/15 Bodies] Downloading block bodies   block_num=38692621 delivery/sec=433.1KB wasted/sec=0B remaining=125033 delivered=163775 cache=68.2MB alloc=3.2GB sys=6.1GB
[INFO] [02-02|09:33:06.837] [txpool] stat                            block=38669522 pending=636 baseFee=332 queued=22295 alloc=3.3GB sys=6.1GB
[INFO] [02-02|09:33:17.576] [5/15 Bodies] Downloading block bodies   block_num=38694215 delivery/sec=58.4MB wasted/sec=0B remaining=123439 delivered=183619 cache=256.0MB alloc=4.1GB sys=6.1GB
[INFO] [02-02|09:33:37.587] [5/15 Bodies] Downloading block bodies   block_num=38695457 delivery/sec=137.7MB wasted/sec=0B remaining=122197 delivered=231576 cache=256.0MB alloc=4.3GB sys=6.3GB
[INFO] [02-02|09:33:57.571] [5/15 Bodies] Downloading block bodies   block_num=38699160 delivery/sec=107.9MB wasted/sec=0B remaining=118494 delivered=272538 cache=256.0MB alloc=4.3GB sys=6.3GB
[INFO] [02-02|09:34:03.102] [p2p] GoodPeers                          eth66=37
[INFO] [02-02|09:34:06.841] [txpool] stat                            block=38669522 pending=730 baseFee=384 queued=24298 alloc=3.4GB sys=6.3GB
[INFO] [02-02|09:34:17.570] [5/15 Bodies] Downloading block bodies   block_num=38699555 delivery/sec=35.6MB wasted/sec=0B remaining=118099 delivered=285536 cache=256.0MB alloc=2.7GB sys=6.3GB
[INFO] [02-02|09:34:37.571] [5/15 Bodies] Downloading block bodies   block_num=38700097 delivery/sec=25.0MB wasted/sec=0B remaining=117557 delivered=294047 cache=256.0MB alloc=2.6GB sys=6.3GB
[INFO] [02-02|09:34:57.570] [5/15 Bodies] Downloading block bodies   block_num=38700097 delivery/sec=746.6KB wasted/sec=0B remaining=117557 delivered=294299 cache=256.0MB alloc=2.8GB sys=6.3GB
[INFO] [02-02|09:35:06.837] [txpool] stat                            block=38669522 pending=1050 baseFee=439 queued=30000 alloc=2.9GB sys=6.3GB
[INFO] [02-02|09:35:17.571] [5/15 Bodies] Downloading block bodies   block_num=38700098 delivery/sec=266.0KB wasted/sec=0B remaining=117557 delivered=294365 cache=255.9MB alloc=3.0GB sys=6.3GB
[INFO] [02-02|09:35:37.570] [5/15 Bodies] Downloading block bodies   block_num=38700223 delivery/sec=539.9KB wasted/sec=0B remaining=117432 delivered=294487 cache=253.9MB alloc=3.1GB sys=6.3GB
[INFO] [02-02|09:35:57.595] [5/15 Bodies] Downloading block bodies   block_num=38704229 delivery/sec=41.7MB wasted/sec=0B remaining=113425 delivered=309320 cache=256.0MB alloc=4.6GB sys=6.3GB
[INFO] [02-02|09:36:03.102] [p2p] GoodPeers                          eth66=40
[INFO] [02-02|09:36:06.841] [txpool] stat                            block=38669522 pending=1139 baseFee=469 queued=30000 alloc=4.4GB sys=6.3GB
[INFO] [02-02|09:36:17.629] [5/15 Bodies] Downloading block bodies   block_num=38704942 delivery/sec=122.1MB wasted/sec=0B remaining=112712 delivered=352445 cache=256.0MB alloc=3.5GB sys=6.3GB
[INFO] [02-02|09:36:37.581] [5/15 Bodies] Downloading block bodies   block_num=38711149 delivery/sec=105.2MB wasted/sec=0B remaining=106505 delivered=391841 cache=256.0MB alloc=3.1GB sys=6.3GB
[INFO] [02-02|09:36:57.570] [5/15 Bodies] Downloading block bodies   block_num=38715481 delivery/sec=55.3MB wasted/sec=0B remaining=102173 delivered=412064 cache=256.0MB alloc=3.2GB sys=6.3GB
[INFO] [02-02|09:37:06.837] [txpool] stat                            block=38669522 pending=1520 baseFee=470 queued=30000 alloc=3.4GB sys=6.3GB
[INFO] [02-02|09:37:17.571] [5/15 Bodies] Downloading block bodies   block_num=38715481 delivery/sec=1.6MB wasted/sec=0B remaining=102173 delivered=412711 cache=256.0MB alloc=3.5GB sys=6.3GB
[INFO] [02-02|09:37:37.571] [5/15 Bodies] Downloading block bodies   block_num=38717725 delivery/sec=52.5MB wasted/sec=0B remaining=99929 delivered=431612 cache=256.0MB alloc=3.8GB sys=6.3GB
[INFO] [02-02|09:37:57.577] [5/15 Bodies] Downloading block bodies   block_num=38717725 delivery/sec=138.3MB wasted/sec=0B remaining=99929 delivered=480594 cache=256.0MB alloc=3.8GB sys=6.3GB
[INFO] [02-02|09:38:03.102] [p2p] GoodPeers                          eth66=47
[INFO] [02-02|09:38:06.843] [txpool] stat                            block=38669522 pending=1613 baseFee=471 queued=30000 alloc=4.0GB sys=6.3GB
[INFO] [02-02|09:38:17.571] [5/15 Bodies] Downloading block bodies   block_num=38725759 delivery/sec=37.6MB wasted/sec=0B remaining=91895 delivered=494873 cache=256.0MB alloc=4.9GB sys=6.3GB
[INFO] [02-02|09:38:37.570] [5/15 Bodies] Downloading block bodies   block_num=38725759 delivery/sec=716.4KB wasted/sec=0B remaining=91895 delivered=495121 cache=256.0MB alloc=2.7GB sys=6.3GB
[INFO] [02-02|09:38:57.570] [5/15 Bodies] Downloading block bodies   block_num=38726552 delivery/sec=11.8MB wasted/sec=0B remaining=91102 delivered=499220 cache=255.9MB alloc=3.9GB sys=6.3GB
[INFO] [02-02|09:39:06.837] [txpool] stat                            block=38669522 pending=3207 baseFee=492 queued=30000 alloc=4.5GB sys=6.3GB
[INFO] [02-02|09:39:17.570] [5/15 Bodies] Downloading block bodies   block_num=38733456 delivery/sec=71.8MB wasted/sec=0B remaining=84198 delivered=524061 cache=256.0MB alloc=3.9GB sys=6.3GB
[INFO] [02-02|09:39:37.571] [5/15 Bodies] Downloading block bodies   block_num=38738789 delivery/sec=31.6MB wasted/sec=0B remaining=78865 delivered=534763 cache=193.9MB alloc=4.7GB sys=6.3GB
[INFO] [02-02|09:39:57.571] [5/15 Bodies] Downloading block bodies   block_num=38741211 delivery/sec=8.9MB wasted/sec=0B remaining=76444 delivered=537444 cache=221.1MB alloc=2.8GB sys=6.3GB
[INFO] [02-02|09:40:03.102] [p2p] GoodPeers                          eth66=55
[INFO] [02-02|09:40:06.842] [txpool] stat                            block=38669522 pending=3951 baseFee=495 queued=30000 alloc=2.9GB sys=6.3GB
[INFO] [02-02|09:40:17.581] [5/15 Bodies] Downloading block bodies   block_num=38743970 delivery/sec=36.9MB wasted/sec=0B remaining=73684 delivered=550367 cache=256.0MB alloc=4.1GB sys=6.3GB
[INFO] [02-02|09:40:37.571] [5/15 Bodies] Writing block bodies       block_num=38750239 remaining=67416 alloc=4.1GB sys=6.4GB
[INFO] [02-02|09:40:57.573] [5/15 Bodies] Downloading block bodies   block_num=38756859 delivery/sec=142.7MB wasted/sec=0B remaining=60795 delivered=602207 cache=256.0MB alloc=4.5GB sys=6.4GB
[INFO] [02-02|09:41:06.850] [txpool] stat                            block=38669522 pending=4103 baseFee=496 queued=30000 alloc=3.4GB sys=6.4GB
[INFO] [02-02|09:41:17.577] [5/15 Bodies] Downloading block bodies   block_num=38764093 delivery/sec=55.0MB wasted/sec=0B remaining=53561 delivered=621700 cache=256.0MB alloc=4.6GB sys=6.4GB
[INFO] [02-02|09:41:37.570] [5/15 Bodies] Downloading block bodies   block_num=38764093 delivery/sec=66.1MB wasted/sec=0B remaining=53561 delivered=647736 cache=256.0MB alloc=3.1GB sys=6.4GB
[INFO] [02-02|09:41:57.571] [5/15 Bodies] Writing block bodies       block_num=38766187 remaining=51468 alloc=3.4GB sys=6.4GB
[INFO] [02-02|09:42:03.102] [p2p] GoodPeers                          eth66=63
[INFO] [02-02|09:42:06.843] [txpool] stat                            block=38669522 pending=4287 baseFee=497 queued=30000 alloc=4.6GB sys=6.4GB
[INFO] [02-02|09:42:17.571] [5/15 Bodies] Downloading block bodies   block_num=38771674 delivery/sec=16.3MB wasted/sec=0B remaining=45980 delivered=653525 cache=55.3MB alloc=5.0GB sys=6.4GB
[INFO] [02-02|09:42:37.571] [5/15 Bodies] Writing block bodies       block_num=38775674 remaining=41981 alloc=3.3GB sys=6.4GB
[INFO] [02-02|09:42:57.595] [5/15 Bodies] Downloading block bodies   block_num=38779042 delivery/sec=115.3MB wasted/sec=0B remaining=38612 delivered=698051 cache=256.0MB alloc=3.3GB sys=6.4GB
[INFO] [02-02|09:43:06.837] [txpool] stat                            block=38669522 pending=4376 baseFee=497 queued=30000 alloc=3.7GB sys=6.4GB
[INFO] [02-02|09:43:17.571] [5/15 Bodies] Downloading block bodies   block_num=38779413 delivery/sec=5.0MB wasted/sec=0B remaining=38241 delivered=699996 cache=255.6MB alloc=3.9GB sys=6.4GB
[INFO] [02-02|09:43:37.571] [5/15 Bodies] Writing block bodies       block_num=38784621 remaining=33034 alloc=4.7GB sys=6.4GB
[INFO] [02-02|09:43:57.570] [5/15 Bodies] Downloading block bodies   block_num=38788084 delivery/sec=88.6MB wasted/sec=0B remaining=29570 delivered=734869 cache=256.0MB alloc=4.6GB sys=6.4GB
[INFO] [02-02|09:44:03.102] [p2p] GoodPeers                          eth66=70
[INFO] [02-02|09:44:06.842] [txpool] stat                            block=38669522 pending=4510 baseFee=497 queued=30000 alloc=4.8GB sys=6.4GB
[INFO] [02-02|09:44:17.570] [5/15 Bodies] Downloading block bodies   block_num=38788423 delivery/sec=4.3MB wasted/sec=0B remaining=29231 delivered=736586 cache=256.0MB alloc=2.7GB sys=6.4GB
[INFO] [02-02|09:44:37.571] [5/15 Bodies] Downloading block bodies   block_num=38791486 delivery/sec=1.3MB wasted/sec=0B remaining=26168 delivered=737102 cache=116.5MB alloc=3.0GB sys=6.4GB
[INFO] [02-02|09:44:57.570] [5/15 Bodies] No block bodies to write in this log period block number=38791486
[INFO] [02-02|09:45:06.837] [txpool] stat                            block=38669522 pending=4748 baseFee=498 queued=30000 alloc=3.2GB sys=6.4GB
[INFO] [02-02|09:45:17.576] [5/15 Bodies] Downloading block bodies   block_num=38792983 delivery/sec=5.1MB wasted/sec=0B remaining=24671 delivered=739135 cache=147.1MB alloc=3.7GB sys=6.4GB
[INFO] [02-02|09:45:37.571] [5/15 Bodies] Downloading block bodies   block_num=38793818 delivery/sec=51.3MB wasted/sec=0B remaining=23836 delivered=759884 cache=256.0MB alloc=3.6GB sys=6.4GB
[INFO] [02-02|09:45:57.570] [5/15 Bodies] Downloading block bodies   block_num=38794409 delivery/sec=1.2MB wasted/sec=0B remaining=23289 delivered=760380 cache=235.4MB alloc=3.8GB sys=6.4GB
[INFO] [02-02|09:46:03.102] [p2p] GoodPeers                          eth66=78
[INFO] [02-02|09:46:08.207] [txpool] stat                            block=38669522 pending=4854 baseFee=511 queued=30000 alloc=4.1GB sys=6.4GB
[INFO] [02-02|09:46:17.570] [5/15 Bodies] Downloading block bodies   block_num=38798672 delivery/sec=19.9MB wasted/sec=0B remaining=18982 delivered=768472 cache=256.0MB alloc=3.8GB sys=6.4GB
[INFO] [02-02|09:46:37.570] [5/15 Bodies] Downloading block bodies   block_num=38798672 delivery/sec=842.1KB wasted/sec=0B remaining=18982 delivered=768787 cache=256.0MB alloc=4.0GB sys=6.4GB
[INFO] [02-02|09:46:57.571] [5/15 Bodies] Downloading block bodies   block_num=38802943 delivery/sec=5.3MB wasted/sec=0B remaining=14711 delivered=770963 cache=122.4MB alloc=4.7GB sys=6.4GB
[INFO] [02-02|09:47:06.837] [txpool] stat                            block=38669522 pending=5376 baseFee=511 queued=30000 alloc=4.8GB sys=6.4GB
[INFO] [02-02|09:47:17.571] [5/15 Bodies] Writing block bodies       block_num=38804423 remaining=13232 alloc=2.6GB sys=6.4GB
[INFO] [02-02|09:47:37.571] [5/15 Bodies] Downloading block bodies   block_num=38804593 delivery/sec=446.2KB wasted/sec=0B remaining=13061 delivered=771133 cache=46.9MB alloc=2.8GB sys=6.4GB
[INFO] [02-02|09:47:57.570] [5/15 Bodies] Downloading block bodies   block_num=38804635 delivery/sec=102.6KB wasted/sec=0B remaining=13019 delivered=771175 cache=46.9MB alloc=3.2GB sys=6.4GB
[INFO] [02-02|09:48:03.102] [p2p] GoodPeers                          eth66=84
[INFO] [02-02|09:48:06.845] [txpool] stat                            block=38669522 pending=5468 baseFee=511 queued=30000 alloc=3.3GB sys=6.4GB
[INFO] [02-02|09:48:17.571] [5/15 Bodies] No block bodies to write in this log period block number=38804635
[INFO] [02-02|09:48:37.575] [5/15 Bodies] Downloading block bodies   block_num=38804871 delivery/sec=15.9MB wasted/sec=0B remaining=12783 delivered=777718 cache=256.0MB alloc=3.4GB sys=6.4GB
[INFO] [02-02|09:48:57.571] [5/15 Bodies] Downloading block bodies   block_num=38804871 delivery/sec=11.8MB wasted/sec=0B remaining=12783 delivered=782549 cache=256.0MB alloc=4.7GB sys=6.4GB
[INFO] [02-02|09:49:06.839] [txpool] stat                            block=38669522 pending=5559 baseFee=511 queued=30000 alloc=4.8GB sys=6.4GB
[INFO] [02-02|09:49:17.571] [5/15 Bodies] Downloading block bodies   block_num=38807513 delivery/sec=1.3MB wasted/sec=0B remaining=10141 delivered=783070 cache=136.8MB alloc=2.9GB sys=6.4GB
[INFO] [02-02|09:49:37.570] [5/15 Bodies] No block bodies to write in this log period block number=38807513
[INFO] [02-02|09:49:57.571] [5/15 Bodies] Downloading block bodies   block_num=38810410 delivery/sec=319.1KB wasted/sec=0B remaining=7244 delivered=783200 cache=6.8MB alloc=3.2GB sys=6.4GB
[INFO] [02-02|09:50:03.102] [p2p] GoodPeers                          eth66=89
[INFO] [02-02|09:50:06.842] [txpool] stat                            block=38669522 pending=5645 baseFee=513 queued=30000 alloc=2.8GB sys=6.4GB
[INFO] [02-02|09:50:17.571] [5/15 Bodies] Downloading block bodies   block_num=38810410 delivery/sec=16.9MB wasted/sec=0B remaining=7244 delivered=790079 cache=256.0MB alloc=3.1GB sys=6.4GB
[INFO] [02-02|09:50:37.570] [5/15 Bodies] Downloading block bodies   block_num=38815842 delivery/sec=1.1MB wasted/sec=0B remaining=1812 delivered=790550 cache=10.2MB alloc=3.3GB sys=6.4GB
[INFO] [02-02|09:50:57.570] [5/15 Bodies] Downloading block bodies   block_num=38816403 delivery/sec=3.8MB wasted/sec=0B remaining=1251 delivered=792097 cache=60.7MB alloc=3.8GB sys=6.4GB
[INFO] [02-02|09:51:06.837] [txpool] stat                            block=38669522 pending=5752 baseFee=513 queued=30000 alloc=3.9GB sys=6.4GB
[INFO] [02-02|09:51:17.570] [5/15 Bodies] Writing block bodies       block_num=38817066 remaining=589 alloc=4.0GB sys=6.4GB
[INFO] [02-02|09:51:29.350] [5/15 Bodies] Processed                  highest=38817655
[INFO] [02-02|09:51:29.350] [5/15 Bodies] DONE                       in=23m31.780861952s
[INFO] [02-02|09:51:29.355] [6/15 Senders] Started                   from=38669681 to=38817655
[INFO] [02-02|09:51:59.355] [6/15 Senders] Recovery                  block_number=38747963 ch=16/10000
[INFO] [02-02|09:52:03.102] [p2p] GoodPeers                          eth66=92
[INFO] [02-02|09:52:06.846] [txpool] stat                            block=38669522 pending=5855 baseFee=514 queued=30000 alloc=4.5GB sys=6.7GB
[INFO] [02-02|09:52:21.927] [7/15 Execution] Blocks execution        from=38669681 to=38817655
[WARN] [02-02|09:52:22.162] [7/15 Execution] Execution failed        block=38669682 hash=0x2ab55d8f89558c478c4c32b58c6d71d9b3378a0f85bb1b74aad388b3226d8651 err="mismatched receipt headers for block 38669682 (0xdde759fe3e4ec594096b001b3486485ce6025bc08b046b2340485bfed4a7ee73 != 0x9aa0d5d12294d2b9bb380928170d4570bbfff446e7b3b9046af2c7362b77f382)"
[INFO] [02-02|09:52:22.162] UnwindTo                                 block=38669681 bad_block_hash=0x2ab55d8f89558c478c4c32b58c6d71d9b3378a0f85bb1b74aad388b3226d8651
[INFO] [02-02|09:52:22.163] [7/15 Execution] Completed on            block=38669681
[INFO] [02-02|09:52:42.164] [5/15 Bodies] Unwinding transactions...  current block=38812114
[INFO] [02-02|09:52:44.878] [2/15 Headers] Waiting for headers...    from=38669681
[INFO] [02-02|09:53:04.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:53:06.837] [txpool] stat                            block=38669522 pending=5978 baseFee=514 queued=30000 alloc=3.2GB sys=7.0GB
[INFO] [02-02|09:53:24.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:53:44.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:54:03.102] [p2p] GoodPeers                          eth66=80
[INFO] [02-02|09:54:04.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:54:06.843] [txpool] stat                            block=38669522 pending=6071 baseFee=514 queued=30000 alloc=3.8GB sys=7.0GB
[INFO] [02-02|09:54:24.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:54:24.879] Req/resp stats                           req=57 reqMin=38669300 reqMax=38797272 skel=17 skelMin=38669681 skelMax=38706545 resp=113 respMin=38189055 respMax=38818363 dups=2908
[INFO] [02-02|09:54:44.878] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:54:44.878] Req/resp stats                           req=58 reqMin=38669274 reqMax=38794764 skel=16 skelMin=38669681 skelMax=38706545 resp=108 respMin=34820768 respMax=38818372 dups=2140
[INFO] [02-02|09:55:04.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:55:04.879] Req/resp stats                           req=48 reqMin=38669256 reqMax=38790530 skel=17 skelMin=38669681 skelMax=38706545 resp=103 respMin=38669258 respMax=38818382 dups=2147
[INFO] [02-02|09:55:06.838] [txpool] stat                            block=38669522 pending=7152 baseFee=515 queued=30000 alloc=2.8GB sys=7.0GB
[INFO] [02-02|09:55:24.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:55:24.879] Req/resp stats                           req=53 reqMin=38669229 reqMax=38786299 skel=18 skelMin=38669681 skelMax=38706545 resp=105 respMin=38189055 respMax=38818391 dups=2334
[INFO] [02-02|09:55:44.878] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:55:44.878] Req/resp stats                           req=65 reqMin=38669198 reqMax=38782644 skel=16 skelMin=38669681 skelMax=38706545 resp=107 respMin=34820768 respMax=38818399 dups=2516
[INFO] [02-02|09:56:03.102] [p2p] GoodPeers                          eth66=93
[INFO] [02-02|09:56:04.878] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:56:04.878] Req/resp stats                           req=54 reqMin=38669168 reqMax=38777264 skel=17 skelMin=38669681 skelMax=38706545 resp=107 respMin=38669171 respMax=38818410 dups=2907
[INFO] [02-02|09:56:06.844] [txpool] stat                            block=38669522 pending=7231 baseFee=515 queued=30000 alloc=3.5GB sys=7.0GB
[INFO] [02-02|09:56:24.878] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:56:24.879] Req/resp stats                           req=49 reqMin=38669143 reqMax=38773802 skel=18 skelMin=38669681 skelMax=38706545 resp=103 respMin=38669145 respMax=38818419 dups=2335
[INFO] [02-02|09:56:44.878] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:56:44.878] Req/resp stats                           req=70 reqMin=38669105 reqMax=38771295 skel=18 skelMin=38669681 skelMax=38706545 resp=130 respMin=38189055 respMax=38818429 dups=2341
[INFO] [02-02|09:57:04.879] [2/15 Headers] No block headers to write in this log period block number=38669681
[INFO] [02-02|09:57:04.879] Req/resp stats                           req=62 reqMin=38669074 reqMax=38765915 skel=17 skelMin=38669681 skelMax=38706545 resp=114 respMin=38669077 respMax=38818438 dups=2717
[INFO] [02-02|09:57:06.838] [txpool] stat                            block=38669522 pending=7311 baseFee=515 queued=30000 alloc=2.9GB sys=7.0GB
```

**Comment by sokiaoba** [comment]
Does this PR  https://github.com/ledgerwatch/erigon/issues/6585#issuecomment-1399480260 only support BSC or can support other networks? 
I'm having a same issue with Polygon archive node (v2.36.1).
